### ISSUE TITLE
Suggestions for improving workshop for next year (2024-5) presentation

### ISSUE THREAD

**Issue by mafeeney** [sipbs-compbiol/BM329_Block_A_workshop#7]
Starting this now while I think on it! A few things that I thought came up in today's workshop (2024) were:

1. -"exact matches" from pubMLST: the MyPlace quiz question confused several students, it would be good if this were reworded to include the table header from the website

Suggestions for improvements for future year:

1. -possibility of adding additional organisms' sequences to analyse (stretch goals for those who are fast at working through the materials; revision or additional practice problems students can work through at home). This could be including other organisms, or other genome isolates of _Brucella/Ochrobactrum_ to give students some idea of the diversity of different diagnostic answers that they might arrive at.
2. -it would be good to explicitly link the material (i.e. via a call-out box in the main text) to:
a. link the material to Koch's postulates and help the students understand that these cannot be formally fulfilled in every case
b. help the students understand the upstream steps required to filter the data (i.e. removing host and kitome sequences
c. clinical micro, i.e. 
[UK SMI for blood cultures](https://assets.publishing.service.gov.uk/media/60a3d3add3bf7f2887b643eb/ID_01_dk+.pdf)
[SENTINEL LEVEL CLINICAL LABORATORY GUIDELINES FOR SUSPECTED AGENTS OF BIOTERRORISM  AND  EMERGING INFECTIOUS DISEASES  Brucella species - ASM](https://asm.org/ASM/media/Policy-and-Advocacy/LRN/Sentinel%20Files/Brucella-2016-March.pdf)
[Brucella: laboratory and clinical services -gov.uk guidance](https://www.gov.uk/guidance/bru-reference-services)

3. it would be good, I think, to add a question to the quiz asking the students to make a final recommendation over whether the patient should be prescribed the antibiotic treatment or not, perhaps with a callout/link to appropriate prescribing guidelines
4.

**Comment by widdowquinn** [comment]
Thanks @mafeeney!

I think point 1 relates to #3 - and I agree.

Likewise I agree with point 2, which links to #2 - I like the links, as well. I'll add these to #2 to keep them together and in the Project overview.

Point 3 is good, too. I'll start an issue for that (just to be tidy and keep achievable issues separate for the sake of management through this process)

**Comment by widdowquinn** [comment]
These are covered under other issues now, so closing. (Feel free to reopen if we need to)
